// Generated by Wrangler on Thu Mar 28 2024 23:12:34 GMT+0100 (středoevropský standardní čas)
// by running `wrangler types ./src/worker-configuration.d.ts`

interface Env {
	CAISY_WEBHOOK_AUTH_KEY: string;
	CLOUDFLARE_PREVIEW_BUILD_HOOK_URL: string;
	CLOUDFLARE_PROD_BUILD_HOOK_URL: string;
	DISABLE_WEBHOOK_BUILD: string;
}
